### ISSUE TITLE
Autoload expreg-contract

### ISSUE THREAD

**Issue by minad** [casouri/expreg#1]
Hi!

Thank you for this package and your work on Treesitter. I suggest to autoload both expreg-contract and expreg-expand for symmetry and because they are the two entry points to the package. Any plans to put expreg on ELPA/MELPA at some point? Thanks!

**Comment by thisch** [comment]
>  Any plans to put expreg on ELPA/MELPA at some point?

Two weeks ago casouri asked on emacs-devel about a submission to ELPA. It was agreed to add it to ELPA, but it is still not done.

**Comment by casouri** [comment]
Yeah, should be soon. And I'll add autoload, no problem.

**Comment by minad** [comment]
Thanks!

**Comment by casouri** [comment]
Now added to ELPA.
